import type { Metadata } from "next";
import { Schibsted_Grotesk, Inconsolata } from "next/font/google";
import "./globals.css";

const nextSans = Schibsted_Grotesk({
  variable: "--font-next-sans",
  subsets: ["latin"],
});

const nextMono = Inconsolata({
  variable: "--font-next-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nextSans.variable} ${nextMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
